on:
  push: {}
jobs:
  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chan: [stable, experimental]
        commit:
          - v17.0.0
          - v17.0.1
          - v17.0.2
          - e6be2d531 # v18.0.0-alpha
          - 96ca8d915 # v18.0.0-beta
          - f2a59df48 # v18.0.0-rc.0
    env:
      REACT_COMMIT: ${{ matrix.commit }}
      CHAN: ${{ matrix.chan }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: git clone https://github.com/facebook/react.git --branch $REACT_COMMIT --single-branch react
      - run: cd react && yarn install
      - run: cd react && mkdir -p results
      - run: cd react && yarn test -r=$CHAN --env=development --json --outputFile=$OUT_FILE --testLocationInResults
        env:
          OUT_FILE: results/react-tests-${{ env.REACT_COMMIT }}-${{ env.CHAN }}.json
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: react/results/
